#!/bin/sh

FUSE_PC="/usr/local/lib/pkgconfig/fuse.pc"

# Restore link from fuse.pc to osxfuse.pc that might have been removed
ln -sf "osxfuse.pc" "${FUSE_PC}"

# Make sure /usr/local/include and /usr/local/lib are readable
chmod u+rx,g+rx,o+rx "/usr/local/include"
chmod u+rx,g+rx,o+rx "/usr/local/lib"

exit 0
